Ima 20
UKHomeOffice/hof-rds-api pull request #15
Opened 2023-10-05 08:19 UTC by TemitopeAyokuHO

##what
setup ima service in hof-rds-api

##Why
new ima service

##How
Added ima service with migration ,seeds, and db configs

2023-10-18 12:04 UTC, Rhodine-orleans-lindsay requested changes

2023-10-18 12:29 UTC, TemitopeAyokuHO commented on package.json
> +    "db:migrate": "node -r dotenv/config -e 'require(\"./db\").migrate()'",
Done

2023-10-18 12:29 UTC, TemitopeAyokuHO commented on services/ima/migrations/20230928142449_create_saved_applications.js
> +        table.string('submitted_at');
Done

2023-10-24 12:55 UTC, Rhodine-orleans-lindsay approved these changes
lgtm

2023-11-29 17:14 UTC, Rhodine-orleans-lindsay reviewed
can you squash the 2 commits please?

2023-11-29 17:17 UTC, Rhodine-orleans-lindsay commented on services/ima/seeds/01_saved_applications.js
> +          email: 'temitope.ayoku@digital.homeoffice.gov.uk',
I would use a test email

2023-11-29 17:17 UTC, Rhodine-orleans-lindsay commented on services/ima/seeds/01_saved_applications.js
> +          email: 'temitope.ayoku@digital.homeoffice.gov.uk',
I would use a test email

2023-11-30 15:03 UTC, merged